//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmadeusLib.Amadeus_B2BWallet_1AWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Amadeus_B2BWallet_1AWS.IB2BWallet_1AWS")]
    public interface IB2BWallet_1AWS {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IB2BWallet_1AWS/ProcessRequest", ReplyAction="http://tempuri.org/IB2BWallet_1AWS/ProcessRequestResponse")]
        string ProcessRequest(string message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IB2BWallet_1AWS/ProcessRequest", ReplyAction="http://tempuri.org/IB2BWallet_1AWS/ProcessRequestResponse")]
        System.Threading.Tasks.Task<string> ProcessRequestAsync(string message);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IB2BWallet_1AWSChannel : AmadeusLib.Amadeus_B2BWallet_1AWS.IB2BWallet_1AWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class B2BWallet_1AWSClient : System.ServiceModel.ClientBase<AmadeusLib.Amadeus_B2BWallet_1AWS.IB2BWallet_1AWS>, AmadeusLib.Amadeus_B2BWallet_1AWS.IB2BWallet_1AWS {
        
        public B2BWallet_1AWSClient() {
        }
        
        public B2BWallet_1AWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public B2BWallet_1AWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public B2BWallet_1AWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public B2BWallet_1AWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string ProcessRequest(string message) {
            return base.Channel.ProcessRequest(message);
        }
        
        public System.Threading.Tasks.Task<string> ProcessRequestAsync(string message) {
            return base.Channel.ProcessRequestAsync(message);
        }
    }
}
