//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión del motor en tiempo de ejecución:2.0.50727.5485
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=2.0.50727.42.
// 


/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class KIU_TravelItineraryRS {
    
    private object successField;
    
    private KIU_TravelItineraryRSItineraryInfo itineraryInfoField;
    
    private KIU_TravelItineraryRSTravelItinerary travelItineraryField;
    
    private KIU_TravelItineraryRSError errorField;
    
    private byte echoTokenField;
    
    private System.DateTime timeStampField;
    
    private string targetField;
    
    private decimal versionField;
    
    private byte sequenceNmbrField;
    
    /// <comentarios/>
    public object Success {
        get {
            return this.successField;
        }
        set {
            this.successField = value;
        }
    }
    
    /// <comentarios/>
    public KIU_TravelItineraryRSItineraryInfo ItineraryInfo {
        get {
            return this.itineraryInfoField;
        }
        set {
            this.itineraryInfoField = value;
        }
    }
    
    /// <comentarios/>
    public KIU_TravelItineraryRSTravelItinerary TravelItinerary {
        get {
            return this.travelItineraryField;
        }
        set {
            this.travelItineraryField = value;
        }
    }
    
    /// <comentarios/>
    public KIU_TravelItineraryRSError Error {
        get {
            return this.errorField;
        }
        set {
            this.errorField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte EchoToken {
        get {
            return this.echoTokenField;
        }
        set {
            this.echoTokenField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public System.DateTime TimeStamp {
        get {
            return this.timeStampField;
        }
        set {
            this.timeStampField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Target {
        get {
            return this.targetField;
        }
        set {
            this.targetField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal Version {
        get {
            return this.versionField;
        }
        set {
            this.versionField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte SequenceNmbr {
        get {
            return this.sequenceNmbrField;
        }
        set {
            this.sequenceNmbrField = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class KIU_TravelItineraryRSItineraryInfo {
    
    private KIU_TravelItineraryRSItineraryInfoTicketing ticketingField;
    
    /// <comentarios/>
    public KIU_TravelItineraryRSItineraryInfoTicketing Ticketing {
        get {
            return this.ticketingField;
        }
        set {
            this.ticketingField = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class KIU_TravelItineraryRSItineraryInfoTicketing {
    
    private string ticketAdvisoryField;
    
    /// <comentarios/>
    public string TicketAdvisory {
        get {
            return this.ticketAdvisoryField;
        }
        set {
            this.ticketAdvisoryField = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class KIU_TravelItineraryRSTravelItinerary {
    
    private KIU_TravelItineraryRSTravelItineraryItineraryRef itineraryRefField;
    
    private KIU_TravelItineraryRSTravelItineraryCustomerInfo[] customerInfosField;
    
    private KIU_TravelItineraryRSTravelItineraryItineraryInfo itineraryInfoField;
    
    private string[] remarksField;
    
    /// <comentarios/>
    public KIU_TravelItineraryRSTravelItineraryItineraryRef ItineraryRef {
        get {
            return this.itineraryRefField;
        }
        set {
            this.itineraryRefField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlArrayItemAttribute("CustomerInfo", IsNullable=false)]
    public KIU_TravelItineraryRSTravelItineraryCustomerInfo[] CustomerInfos {
        get {
            return this.customerInfosField;
        }
        set {
            this.customerInfosField = value;
        }
    }
    
    /// <comentarios/>
    public KIU_TravelItineraryRSTravelItineraryItineraryInfo ItineraryInfo {
        get {
            return this.itineraryInfoField;
        }
        set {
            this.itineraryInfoField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Remark", IsNullable=false)]
    public string[] Remarks {
        get {
            return this.remarksField;
        }
        set {
            this.remarksField = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class KIU_TravelItineraryRSTravelItineraryItineraryRef {
    
    private byte typeField;
    
    private string idField;
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte Type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ID {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class KIU_TravelItineraryRSTravelItineraryCustomerInfo {
    
    private KIU_TravelItineraryRSTravelItineraryCustomerInfoCustomer customerField;
    
    private byte rPHField;
    
    /// <comentarios/>
    public KIU_TravelItineraryRSTravelItineraryCustomerInfoCustomer Customer {
        get {
            return this.customerField;
        }
        set {
            this.customerField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte RPH {
        get {
            return this.rPHField;
        }
        set {
            this.rPHField = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class KIU_TravelItineraryRSTravelItineraryCustomerInfoCustomer {
    
    private KIU_TravelItineraryRSTravelItineraryCustomerInfoCustomerPersonName personNameField;
    
    private KIU_TravelItineraryRSTravelItineraryCustomerInfoCustomerDocument documentField;
    
    private KIU_TravelItineraryRSTravelItineraryCustomerInfoCustomerContactPerson contactPersonField;
    
    private string passengerTypeCodeField;
    
    /// <comentarios/>
    public KIU_TravelItineraryRSTravelItineraryCustomerInfoCustomerPersonName PersonName {
        get {
            return this.personNameField;
        }
        set {
            this.personNameField = value;
        }
    }
    
    /// <comentarios/>
    public KIU_TravelItineraryRSTravelItineraryCustomerInfoCustomerDocument Document {
        get {
            return this.documentField;
        }
        set {
            this.documentField = value;
        }
    }
    
    /// <comentarios/>
    public KIU_TravelItineraryRSTravelItineraryCustomerInfoCustomerContactPerson ContactPerson {
        get {
            return this.contactPersonField;
        }
        set {
            this.contactPersonField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string PassengerTypeCode {
        get {
            return this.passengerTypeCodeField;
        }
        set {
            this.passengerTypeCodeField = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class KIU_TravelItineraryRSTravelItineraryCustomerInfoCustomerPersonName {
    
    private string surnameField;
    
    private string givenNameField;
    
    /// <comentarios/>
    public string Surname {
        get {
            return this.surnameField;
        }
        set {
            this.surnameField = value;
        }
    }
    
    /// <comentarios/>
    public string GivenName {
        get {
            return this.givenNameField;
        }
        set {
            this.givenNameField = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class KIU_TravelItineraryRSTravelItineraryCustomerInfoCustomerDocument {
    
    private string docTypeField;

    private string docIDField;
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string DocType {
        get {
            return this.docTypeField;
        }
        set {
            this.docTypeField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string DocID {
        get {
            return this.docIDField;
        }
        set {
            this.docIDField = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class KIU_TravelItineraryRSTravelItineraryCustomerInfoCustomerContactPerson {
    
    private string telephoneField;
    
    /// <comentarios/>
    public string Telephone {
        get {
            return this.telephoneField;
        }
        set {
            this.telephoneField = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class KIU_TravelItineraryRSTravelItineraryItineraryInfo {
    
    private KIU_TravelItineraryRSTravelItineraryItineraryInfoItem[] reservationItemsField;
    
    private KIU_TravelItineraryRSTravelItineraryItineraryInfoItineraryPricing itineraryPricingField;
    
    private KIU_TravelItineraryRSTravelItineraryItineraryInfoTicketing[] ticketingField;
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Item", IsNullable=false)]
    public KIU_TravelItineraryRSTravelItineraryItineraryInfoItem[] ReservationItems {
        get {
            return this.reservationItemsField;
        }
        set {
            this.reservationItemsField = value;
        }
    }
    
    /// <comentarios/>
    public KIU_TravelItineraryRSTravelItineraryItineraryInfoItineraryPricing ItineraryPricing {
        get {
            return this.itineraryPricingField;
        }
        set {
            this.itineraryPricingField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute("Ticketing")]
    public KIU_TravelItineraryRSTravelItineraryItineraryInfoTicketing[] Ticketing {
        get {
            return this.ticketingField;
        }
        set {
            this.ticketingField = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class KIU_TravelItineraryRSTravelItineraryItineraryInfoItem {
    
    private KIU_TravelItineraryRSTravelItineraryItineraryInfoItemAir airField;
    
    private byte itinSeqNumberField;
    
    /// <comentarios/>
    public KIU_TravelItineraryRSTravelItineraryItineraryInfoItemAir Air {
        get {
            return this.airField;
        }
        set {
            this.airField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte ItinSeqNumber {
        get {
            return this.itinSeqNumberField;
        }
        set {
            this.itinSeqNumberField = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class KIU_TravelItineraryRSTravelItineraryItineraryInfoItemAir {
    
    private KIU_TravelItineraryRSTravelItineraryItineraryInfoItemAirReservation reservationField;
    
    /// <comentarios/>
    public KIU_TravelItineraryRSTravelItineraryItineraryInfoItemAirReservation Reservation {
        get {
            return this.reservationField;
        }
        set {
            this.reservationField = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class KIU_TravelItineraryRSTravelItineraryItineraryInfoItemAirReservation {
    
    private KIU_TravelItineraryRSTravelItineraryItineraryInfoItemAirReservationDepartureAirport departureAirportField;
    
    private KIU_TravelItineraryRSTravelItineraryItineraryInfoItemAirReservationArrivalAirport arrivalAirportField;
    
    private string marketingAirlineField;
    
    private System.DateTime departureDateTimeField;
    
    private System.DateTime arrivalDateTimeField;
    
    private ushort flightNumberField;
    
    private string resBookDesigCodeField;
    
    private byte statusField;
    
    /// <comentarios/>
    public KIU_TravelItineraryRSTravelItineraryItineraryInfoItemAirReservationDepartureAirport DepartureAirport {
        get {
            return this.departureAirportField;
        }
        set {
            this.departureAirportField = value;
        }
    }
    
    /// <comentarios/>
    public KIU_TravelItineraryRSTravelItineraryItineraryInfoItemAirReservationArrivalAirport ArrivalAirport {
        get {
            return this.arrivalAirportField;
        }
        set {
            this.arrivalAirportField = value;
        }
    }
    
    /// <comentarios/>
    public string MarketingAirline {
        get {
            return this.marketingAirlineField;
        }
        set {
            this.marketingAirlineField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public System.DateTime DepartureDateTime {
        get {
            return this.departureDateTimeField;
        }
        set {
            this.departureDateTimeField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public System.DateTime ArrivalDateTime {
        get {
            return this.arrivalDateTimeField;
        }
        set {
            this.arrivalDateTimeField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ushort FlightNumber {
        get {
            return this.flightNumberField;
        }
        set {
            this.flightNumberField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ResBookDesigCode {
        get {
            return this.resBookDesigCodeField;
        }
        set {
            this.resBookDesigCodeField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte Status {
        get {
            return this.statusField;
        }
        set {
            this.statusField = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class KIU_TravelItineraryRSTravelItineraryItineraryInfoItemAirReservationDepartureAirport {
    
    private string locationCodeField;
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string LocationCode {
        get {
            return this.locationCodeField;
        }
        set {
            this.locationCodeField = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class KIU_TravelItineraryRSTravelItineraryItineraryInfoItemAirReservationArrivalAirport {
    
    private string locationCodeField;
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string LocationCode {
        get {
            return this.locationCodeField;
        }
        set {
            this.locationCodeField = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class KIU_TravelItineraryRSTravelItineraryItineraryInfoItineraryPricing {
    
    private KIU_TravelItineraryRSTravelItineraryItineraryInfoItineraryPricingCost costField;
    
    private KIU_TravelItineraryRSTravelItineraryItineraryInfoItineraryPricingTax[] taxesField;
    
    private string feesField;
    
    private string itemRPHListField;
    
    /// <comentarios/>
    public KIU_TravelItineraryRSTravelItineraryItineraryInfoItineraryPricingCost Cost {
        get {
            return this.costField;
        }
        set {
            this.costField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Tax", IsNullable=false)]
    public KIU_TravelItineraryRSTravelItineraryItineraryInfoItineraryPricingTax[] Taxes {
        get {
            return this.taxesField;
        }
        set {
            this.taxesField = value;
        }
    }
    
    /// <comentarios/>
    public string Fees {
        get {
            return this.feesField;
        }
        set {
            this.feesField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ItemRPHList {
        get {
            return this.itemRPHListField;
        }
        set {
            this.itemRPHListField = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class KIU_TravelItineraryRSTravelItineraryItineraryInfoItineraryPricingCost {
    
    private decimal amountBeforeTaxField;
    
    private decimal amountAfterTaxField;
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal AmountBeforeTax {
        get {
            return this.amountBeforeTaxField;
        }
        set {
            this.amountBeforeTaxField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal AmountAfterTax {
        get {
            return this.amountAfterTaxField;
        }
        set {
            this.amountAfterTaxField = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class KIU_TravelItineraryRSTravelItineraryItineraryInfoItineraryPricingTax {
    
    private string taxCodeField;
    
    private decimal amountField;
    
    private string currencyCodeField;
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string TaxCode {
        get {
            return this.taxCodeField;
        }
        set {
            this.taxCodeField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal Amount {
        get {
            return this.amountField;
        }
        set {
            this.amountField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string CurrencyCode {
        get {
            return this.currencyCodeField;
        }
        set {
            this.currencyCodeField = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class KIU_TravelItineraryRSTravelItineraryItineraryInfoTicketing {
    
    private string ticketAdvisoryField;
    
    private string[] textField;
    
    private byte ticketingStatusField;
    
    private System.DateTime ticketTimeLimitField;
    
    private string ticketTypeField;
    
    private ulong eTicketNumberField;
    
    private byte travelerRefNumberField;
    
    /// <comentarios/>
    public string TicketAdvisory {
        get {
            return this.ticketAdvisoryField;
        }
        set {
            this.ticketAdvisoryField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string[] Text {
        get {
            return this.textField;
        }
        set {
            this.textField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte TicketingStatus {
        get {
            return this.ticketingStatusField;
        }
        set {
            this.ticketingStatusField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public System.DateTime TicketTimeLimit {
        get {
            return this.ticketTimeLimitField;
        }
        set {
            this.ticketTimeLimitField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string TicketType {
        get {
            return this.ticketTypeField;
        }
        set {
            this.ticketTypeField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ulong eTicketNumber {
        get {
            return this.eTicketNumberField;
        }
        set {
            this.eTicketNumberField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte TravelerRefNumber {
        get {
            return this.travelerRefNumberField;
        }
        set {
            this.travelerRefNumberField = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class KIU_TravelItineraryRSError {
    
    private ushort errorCodeField;
    
    private string errorMsgField;
    
    /// <comentarios/>
    public ushort ErrorCode {
        get {
            return this.errorCodeField;
        }
        set {
            this.errorCodeField = value;
        }
    }
    
    /// <comentarios/>
    public string ErrorMsg {
        get {
            return this.errorMsgField;
        }
        set {
            this.errorMsgField = value;
        }
    }
}
